name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug SSH Setup
        run: |
          echo "Checking current user and permissions"
          whoami
          ls -la ~/
          ls -la ~/.ssh || echo "No .ssh directory found"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Copy Project to Multipass VM
        run: |
          scp -r . ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/hngx-stage2-deploy-fastapi

      - name: Restart API & Nginx
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ubuntu/hngx-stage2-deploy-fastapi
          source venv/bin/activate
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > log.txt 2>&1 &
          sudo systemctl restart nginx
          EOF

#
