name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to AWS Server
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no moneim@54.245.237.108 << 'EOF'
          cd ~/hngx-stage2-deploy-fastapi
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          echo "" | sudo -S systemctl restart nginx
          echo "" | sudo -S systemctl restart fastapi  # Replace with actual service name
          EOF
