name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Project to Multipass VM
        run: |
          scp -r . ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/hngx-stage2-deploy-fastapi

      - name: Restart API & Nginx
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ubuntu/hngx-stage2-deploy-fastapi
          source venv/bin/activate
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > log.txt 2>&1 &
          sudo systemctl restart nginx
          EOF
