name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Railway CLI (Retry on Failure)
        run: |
          for i in {1..3}; do
            curl -fsSL https://railway.app/install.sh | sh && break
            echo "Retrying in 5 seconds..."
            sleep 5
          done
          # Ensure Railway CLI is in PATH
          export PATH="$HOME/.railway/bin:$PATH"
          echo "PATH updated to include Railway CLI"

      - name: Verify Railway CLI Installation
        run: |
          export PATH="$HOME/.railway/bin:$PATH"
          railway --version || { echo "Railway CLI failed to install"; exit 1; }

      - name: Authenticate Railway CLI
        run: |
          export PATH="$HOME/.railway/bin:$PATH"
          echo "${{ secrets.RAILWAY_API_TOKEN }}" | railway login --ci

      - name: Link Railway Project
        run: |
          export PATH="$HOME/.railway/bin:$PATH"
          railway link --project 872c4fdc-be05-48e1-a12e-b57a6e5385b5

      - name: Deploy to Railway
        run: |
          export PATH="$HOME/.railway/bin:$PATH"
          railway up --service hngx-stage2-deploy-fastapi
