name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to AWS
        env:
          SSH_HOST: "10.200.156.6"
          SSH_USER: "ubuntu"
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SSH_USER@$SSH_HOST << 'EOF'
            cd ~/hngx-stage2-deploy-fastapi
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart myapi  # Ensure you have a systemd service set up
            sudo systemctl restart nginx
          EOF
